# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: team.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='team.proto',
  package='ssl',
  serialized_pb='\n\nteam.proto\x12\x03ssl\"\x8e\x04\n\x05Robot\x12\x1d\n\x04pose\x18\x01 \x02(\x0b\x32\x0f.ssl.Robot.Pose\x12\x1f\n\x05speed\x18\x02 \x01(\x0b\x32\x10.ssl.Robot.Speed\x12\'\n\x06\x61\x63tion\x18\x03 \x01(\x0e\x32\x11.ssl.Robot.Action:\x04MOVE\x12\x1d\n\x04move\x18\x04 \x01(\x0b\x32\x0f.ssl.Robot.Move\x12\x1d\n\x04pass\x18\x05 \x01(\x0b\x32\x0f.ssl.Robot.Pass\x12\x1d\n\x04kick\x18\x06 \x01(\x0b\x32\x0f.ssl.Robot.Kick\x1a&\n\x08Position\x12\x0c\n\x01x\x18\x01 \x02(\x02:\x01\x30\x12\x0c\n\x01y\x18\x02 \x02(\x02:\x01\x30\x1a<\n\x04Pose\x12%\n\x08position\x18\x01 \x02(\x0b\x32\x13.ssl.Robot.Position\x12\r\n\x05theta\x18\x02 \x01(\x02\x1a=\n\x05Speed\x12#\n\x06linear\x18\x01 \x02(\x0b\x32\x13.ssl.Robot.Position\x12\x0f\n\x07\x61ngular\x18\x02 \x01(\x02\x1a+\n\x04Move\x12#\n\x06target\x18\x01 \x02(\x0b\x32\x13.ssl.Robot.Position\x1a\x18\n\x04Pass\x12\x10\n\x08robot_id\x18\x01 \x02(\x05\x1a+\n\x04Kick\x12#\n\x06target\x18\x01 \x02(\x0b\x32\x13.ssl.Robot.Position\"&\n\x06\x41\x63tion\x12\x08\n\x04MOVE\x10\x00\x12\x08\n\x04PASS\x10\x01\x12\x08\n\x04KICK\x10\x02\"h\n\x04Team\x12&\n\x05\x63olor\x18\x01 \x02(\x0e\x32\x0f.ssl.Team.Color:\x06YELLOW\x12\x19\n\x05robot\x18\x02 \x03(\x0b\x32\n.ssl.Robot\"\x1d\n\x05\x43olor\x12\x08\n\x04\x42LUE\x10\x00\x12\n\n\x06YELLOW\x10\x01')



_ROBOT_ACTION = _descriptor.EnumDescriptor(
  name='Action',
  full_name='ssl.Robot.Action',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MOVE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PASS', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='KICK', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=508,
  serialized_end=546,
)

_TEAM_COLOR = _descriptor.EnumDescriptor(
  name='Color',
  full_name='ssl.Team.Color',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BLUE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='YELLOW', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=623,
  serialized_end=652,
)


_ROBOT_POSITION = _descriptor.Descriptor(
  name='Position',
  full_name='ssl.Robot.Position',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='ssl.Robot.Position.x', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='ssl.Robot.Position.y', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=227,
  serialized_end=265,
)

_ROBOT_POSE = _descriptor.Descriptor(
  name='Pose',
  full_name='ssl.Robot.Pose',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='position', full_name='ssl.Robot.Pose.position', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='theta', full_name='ssl.Robot.Pose.theta', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=267,
  serialized_end=327,
)

_ROBOT_SPEED = _descriptor.Descriptor(
  name='Speed',
  full_name='ssl.Robot.Speed',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='linear', full_name='ssl.Robot.Speed.linear', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='angular', full_name='ssl.Robot.Speed.angular', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=329,
  serialized_end=390,
)

_ROBOT_MOVE = _descriptor.Descriptor(
  name='Move',
  full_name='ssl.Robot.Move',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='target', full_name='ssl.Robot.Move.target', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=392,
  serialized_end=435,
)

_ROBOT_PASS = _descriptor.Descriptor(
  name='Pass',
  full_name='ssl.Robot.Pass',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='robot_id', full_name='ssl.Robot.Pass.robot_id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=437,
  serialized_end=461,
)

_ROBOT_KICK = _descriptor.Descriptor(
  name='Kick',
  full_name='ssl.Robot.Kick',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='target', full_name='ssl.Robot.Kick.target', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=463,
  serialized_end=506,
)

_ROBOT = _descriptor.Descriptor(
  name='Robot',
  full_name='ssl.Robot',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pose', full_name='ssl.Robot.pose', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='speed', full_name='ssl.Robot.speed', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='action', full_name='ssl.Robot.action', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='move', full_name='ssl.Robot.move', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pass', full_name='ssl.Robot.pass', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='kick', full_name='ssl.Robot.kick', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_ROBOT_POSITION, _ROBOT_POSE, _ROBOT_SPEED, _ROBOT_MOVE, _ROBOT_PASS, _ROBOT_KICK, ],
  enum_types=[
    _ROBOT_ACTION,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=20,
  serialized_end=546,
)


_TEAM = _descriptor.Descriptor(
  name='Team',
  full_name='ssl.Team',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='color', full_name='ssl.Team.color', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='robot', full_name='ssl.Team.robot', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TEAM_COLOR,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=548,
  serialized_end=652,
)

_ROBOT_POSITION.containing_type = _ROBOT;
_ROBOT_POSE.fields_by_name['position'].message_type = _ROBOT_POSITION
_ROBOT_POSE.containing_type = _ROBOT;
_ROBOT_SPEED.fields_by_name['linear'].message_type = _ROBOT_POSITION
_ROBOT_SPEED.containing_type = _ROBOT;
_ROBOT_MOVE.fields_by_name['target'].message_type = _ROBOT_POSITION
_ROBOT_MOVE.containing_type = _ROBOT;
_ROBOT_PASS.containing_type = _ROBOT;
_ROBOT_KICK.fields_by_name['target'].message_type = _ROBOT_POSITION
_ROBOT_KICK.containing_type = _ROBOT;
_ROBOT.fields_by_name['pose'].message_type = _ROBOT_POSE
_ROBOT.fields_by_name['speed'].message_type = _ROBOT_SPEED
_ROBOT.fields_by_name['action'].enum_type = _ROBOT_ACTION
_ROBOT.fields_by_name['move'].message_type = _ROBOT_MOVE
_ROBOT.fields_by_name['pass'].message_type = _ROBOT_PASS
_ROBOT.fields_by_name['kick'].message_type = _ROBOT_KICK
_ROBOT_ACTION.containing_type = _ROBOT;
_TEAM.fields_by_name['color'].enum_type = _TEAM_COLOR
_TEAM.fields_by_name['robot'].message_type = _ROBOT
_TEAM_COLOR.containing_type = _TEAM;
DESCRIPTOR.message_types_by_name['Robot'] = _ROBOT
DESCRIPTOR.message_types_by_name['Team'] = _TEAM

class Robot(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType

  class Position(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _ROBOT_POSITION

    # @@protoc_insertion_point(class_scope:ssl.Robot.Position)

  class Pose(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _ROBOT_POSE

    # @@protoc_insertion_point(class_scope:ssl.Robot.Pose)

  class Speed(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _ROBOT_SPEED

    # @@protoc_insertion_point(class_scope:ssl.Robot.Speed)

  class Move(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _ROBOT_MOVE

    # @@protoc_insertion_point(class_scope:ssl.Robot.Move)

  class Pass(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _ROBOT_PASS

    # @@protoc_insertion_point(class_scope:ssl.Robot.Pass)

  class Kick(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _ROBOT_KICK

    # @@protoc_insertion_point(class_scope:ssl.Robot.Kick)
  DESCRIPTOR = _ROBOT

  # @@protoc_insertion_point(class_scope:ssl.Robot)

class Team(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TEAM

  # @@protoc_insertion_point(class_scope:ssl.Team)


# @@protoc_insertion_point(module_scope)
